config/routes.rb
Rails.application.routes.draw do


  root "bands#index"

  resources :bands, only: [:index, :show]
end

app/models/band.rb
class Band < ActiveRecord::Base
  has_many :music_videos
end

app/models/music_video.rb
class MusicVideo < ActiveRecord::Base
  belongs_to :band
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
  end

  def show
    @band = Band.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bands/index.html.erb
<h1>Welcome to Musica Videos!</h1>
<p>Here you can see a list of bands. Click any band to see it's music videos</p>

<ul>
  <% @bands.each do |band| %>
  <li><%=link_to band.name, band_path(band) %></li>
  <% end %>
</ul>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<h3> Genre: <%= @band.genre %></h3>


  <% @band.music_videos.each do |music_videos| %>
  <li>
    <%=link_to music_videos.title %>
  </li>

  <% end %>
</ul>


<footer>

  <%= link_to "Back to Home", root_path %>

</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicaVideoMgmt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>